import { useState } from 'react';
import { useToast } from '@chakra-ui/react';
import { analyzeResponse } from '../api/openai';

/**
 * Custom hook for managing interview response analysis
 * @returns {Object} Analysis methods and state
 */
const useResponseAnalysis = () => {
  // State
  const [feedback, setFeedback] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  
  // Chakra UI toast
  const toast = useToast();

  /**
   * Analyze a user response to an interview question
   * @param {string} question - The interview question
   * @param {string} answer - The user's answer
   */
  const analyzeUserResponse = async (question, answer) => {
    if (!answer || answer === "Transcribing your answer...") {
      toast({
        title: 'Cannot analyze',
        description: 'No valid answer to analyze',
        status: 'warning',
        duration: 3000,
        isClosable: true,
      });
      return;
    }
    
    setIsAnalyzing(true);
    
    try {
      // Get analysis result from API - the exampleAnswer is now generated by the API
      // and included in the response
      const analysisResult = await analyzeResponse(question, answer);
      
      // Logging for debugging
      console.log("Analysis result with AI-generated example:", analysisResult);
      
      setFeedback(analysisResult);
      
      toast({
        title: 'Analysis complete',
        description: 'Your answer has been evaluated',
        status: 'success',
        duration: 3000,
        isClosable: true,
      });
    } catch (error) {
      console.error('Error analyzing response:', error);
      
      // In case of error, provide a default feedback with a placeholder example answer
      const errorFeedback = {
        overallScore: 0,
        generalFeedback: "Sorry, there was an error analyzing your response. Please try again.",
        categories: {},
        additionalMetrics: {},
        improvementSuggestions: ["Try recording again"],
        exampleAnswer: "Example not available due to an error. Please try again."
      };
      
      setFeedback(errorFeedback);
      
      toast({
        title: 'Analysis error',
        description: 'Could not analyze your response',
        status: 'error',
        duration: 5000,
        isClosable: true,
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  /**
   * Reset analysis feedback
   */
  const resetFeedback = () => {
    setFeedback(null);
  };
  
  /**
   * Manually set feedback (for loading from history)
   * @param {Object} feedbackData - The feedback data to set
   */
  const setFeedbackManually = (feedbackData) => {
    setFeedback(feedbackData);
  };

  return {
    // State
    feedback,
    isAnalyzing,
    
    // Methods
    analyzeUserResponse,
    resetFeedback,
    setFeedbackManually, // Added new method
  };
};

export default useResponseAnalysis;